// src/lib/email/templates.ts

export function renderPredictionEmail(opts: {
  name?: string;
  link: string;
  query?: string;
  prediction?: string;
  dob?: string;
}) {
  const { name, link, query, prediction, dob } = opts;

  return `
  <div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,sans-serif;background:#0b1220;color:#e5e7eb;padding:24px">
    <table role="presentation" style="width:100%;max-width:660px;margin:0 auto;background:#0f172a;border-radius:14px;border:1px solid #2b3244">
      <tr>
        <td style="padding:20px 24px;border-bottom:1px solid #222944">
          <div style="font-size:18px;color:#D4AF37;font-weight:700">JyotAI · Brahmin GPT</div>
          <div style="font-size:12px;color:#a7b1c2">Your Divine Reading</div>
        </td>
      </tr>

      <tr>
        <td style="padding:20px 24px">
          <h2 style="margin:0 0 10px;color:#D4AF37">🪔 Greetings${name ? `, ${name}` : ""}</h2>
          <p style="margin:0 0 12px">The cosmos has spoken. Your reading has been recorded in your portal.</p>

          <a href="${link}"
             style="display:inline-block;background:#D4AF37;color:#0b1220;text-decoration:none;font-weight:700;padding:10px 16px;border-radius:10px">
            Enter Your Portal
          </a>

          <div style="margin-top:18px;border-top:1px solid #222944;padding-top:12px">
            <div style="font-size:12px;color:#9aa3b2;margin-bottom:6px">Question</div>
            <div style="color:#e5e7eb">${escapeHtml(query || "—")}</div>

            <div style="font-size:12px;color:#9aa3b2;margin:14px 0 6px">Divine Insight</div>
            <div style="white-space:pre-wrap;color:#e5e7eb">${escapeHtml(prediction || "—")}</div>

            ${dob ? `<div style="margin-top:14px;font-size:12px;color:#9aa3b2">DOB: <span style="color:#e5e7eb">${escapeHtml(dob)}</span></div>` : ""}
          </div>
        </td>
      </tr>

      <tr>
        <td style="padding:16px 24px;color:#94a3b8;font-size:12px;border-top:1px solid #222944">
          Generated by JyotAI · For personal guidance.
        </td>
      </tr>
    </table>
  </div>
  `;
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}
